from thespian.actors import ActorSystemMessage

class EndpointConnected(ActorSystemMessage):
    # internal message sent from child to parent on startup connection
    def __init__(self, childInstance):
        self.childInstance = childInstance


class LoggerConnected(ActorSystemMessage): pass

class ChildMayHaveDied(ActorSystemMessage):
    """Generated by transport layer in response to an interrupt call
       indicating that there may have been a child exit.  The latter
       is typically called by SIGCHLD handling.  Not actually passed
       between actors or admins.
    """
    pass
